### ISSUE TITLE
raw evaluation results

### ISSUE THREAD

**Issue by xiaoyuxin1002** [princeton-nlp/InstructEval#1]
Hi, thanks for this awesome evaluation suite!
Would you mind also sharing the raw evaluation results (i.e., the content in your `RESULTS_DIR` directory used in the `build_raw_df_from_results` function in `notebook/aggregate_results.ipynb`)?
It would be extremely valuable to see how each model performs with each prompt on each dataset.

**Comment by xiaoyuxin1002** [comment]
And it looks like the score is based on 100 data points sampled from the testing split of each dataset. Am I right?

**Comment by anirudhajith** [comment]
Hi @xiaoyuxin1002! I'm glad you like our evaluation suite!

You should be able to access the results (and associated metadata) from a collection of experiments we performed for our paper [here](https://drive.google.com/file/d/1xKuAPfmMrMb7HJeJyT_kEW3mXkj1xzzV/view?usp=sharing). We've also made this link available in the README.

Yup, the example configuration files we've included with the codebase would cause the suite to sample 100 datapoints from the testing split of each dataset as you say. You will be able to find the precise settings of the parameters we used while performing our experiments in the results files.

Please let us know if you have any more questions!

EDIT: Updated link

**Comment by xiaoyuxin1002** [comment]
Hi, after checking the data in the result folder, particularly those related to zero_shot_accuracy.
I found that not all the models or datasets have the same number of evaluations.
Is there a particular reason why that is so? Thanks!

For example, 
```
model
bloom1b1      268
bloom1b7      267
bloom3b       267
bloom7b1      267
gptneo1b3     266
gptneo2b7     267
gptneox20b    266
llama13b      268
llama7b       268
opt13b        268
opt1b3        268
opt2b7        268
opt6b7        268

dataset
ag_news          403
anli             403
boolq            403
cosmos_qa        399
hellaswag        388
imdb             403
nq_open          338
trivia_qa        336
tweet_emotion    403
```

**Comment by anirudhajith** [comment]
Hi @xiaoyuxin1002. I believe the counts you have listed above are incorrect due to a subtle miscount of the `low
_perplexity_prompts` instructions. Unlike other methods we evaluate, each model is associated with its own set of instructions for the `low_perplexity_prompts` method. There may even be some overlap between the low perplexity instructions chosen by different models due to correlations in these perplexity values.

I used this code snippet
```python3
METRIC = "zero_shot_accuracy"
RESULTS_DIR = "results/"

for filename in tqdm(os.listdir(RESULTS_DIR)):
    record = json.loads(open(os.path.join(RESULTS_DIR, filename), "r").read())
    model = record["metadata"]["model"]
    dataset = record["metadata"]["dataset"]
    instructions_dir = record["metadata"]["instructions_dir"]
    metric = record["metadata"]["metric"]
    if metric == METRIC:
        if model in stats_by_model:
            stats_by_model[model] += 1
        else:
            stats_by_model[model] = 1
            
        if dataset in stats_by_dataset:
            stats_by_dataset[dataset] += 1
        else:
            stats_by_dataset[dataset] = 1

        if instructions_dir in stats_by_instruction_dir:
            stats_by_instruction_dir[instructions_dir] += 1
        else:
            stats_by_instruction_dir[instructions_dir] = 1
            
        if metric in stats_by_metric:
            stats_by_metric[metric] += 1
        else:
            stats_by_metric[metric] = 1
        
print(f"{METRIC} metric counts:")
print(f"By model: {json.dumps(stats_by_model, indent=1)}")
print(f"By dataset: {json.dumps(stats_by_dataset, indent=1)}")
print(f"By instructions_dir: {json.dumps(stats_by_instruction_dir, indent=1)}")
print(f"By metric: {json.dumps(stats_by_metric, indent=1)}")
```
to obtain the following counts for `zero_shot_accuracy`:
```
zero_shot_accuracy metric counts:
By model: {
 "bloom3b": 269,
 "opt6b7": 269,
 "bloom1b7": 269,
 "opt2b7": 269,
 "opt13b": 269,
 "gptneo2b7": 269,
 "gptneox20b": 269,
 "bloom7b1": 269,
 "opt1b3": 269,
 "llama7b": 269,
 "bloom1b1": 269,
 "gptneo1b3": 269,
 "llama13b": 269
}
By dataset: {
 "cosmos_qa": 403,
 "hellaswag": 403,
 "nq_open": 338,
 "ag_news": 403,
 "imdb": 403,
 "tweet_emotion": 403,
 "boolq": 403,
 "anli": 403,
 "trivia_qa": 338
}
By instructions_dir: {
 "instructions/generic_instruction": 585,
 "instructions/manual": 585,
 "instructions/chat_gpt_prompts": 585,
 "instructions/low_perplexity_prompts": 585,
 "instructions/ape": 585,
 "instructions/rlprompt": 455,
 "instructions/no_instruction": 117
}
By metric: {
 "zero_shot_accuracy": 3497
}
```
These are indeed the expected numbers of files corresponding to each of these parameters. We evaluate 5 metrics for each of our 13 models. We perform evaluations over all the methods for the CLS and MCQ tasks we consider. However as noted in our paper, we do not evaluate `rlprompt` on GQA tasks since the associated algorithm isn't directly applicable to generation tasks. We evaluate 5 instructions corresponding to each method (per (model, dataset) pair) for all methods except no_instruction for which we only perform only a single evaluation.

Taking all of this into account, the expected number of results files per metric is 
```
13×(7×(6×5+1×1)+2×(5×5+1×1)) = 3497
```
which matches with the counts obtained above. The total number of results files expected is thus 5 × 3497 = 17485.

I discovered that 10 out of our 17485 files were in fact missing from the folder at the link I shared with you yesterday. Apologies for this. I have uploaded a new folder containing all the results [here](https://drive.google.com/file/d/1xKuAPfmMrMb7HJeJyT_kEW3mXkj1xzzV/view?usp=sharing). I have also added a function called `print_results_dir_statistic_by_metric()` that can be used to check the number of evaluations to `notebooks/aggregate_results.ipynb` which you should be able to use after pulling the latest commit.

Please let me know if this clears everything up and if you have any more questions.

**Comment by xiaoyuxin1002** [comment]
Thank you very much for this detailed explanation! It clears all of my doubts!
